name: 'New Relic Upload Sourcemap Action'
description: 'Upload a sourcemap to New Relic'
branding:
  icon: 'upload'
  color: 'gray-dark'
inputs:
  new_relic_user_api_key:
    description: 'A valid user API key'
    required: true
  new_relic_app_id:
    description: 'A valid application id'
    required: true
  sourcemap_path:
    description: 'Path to the sourcemap file'
    required: true
  javascript_url:
    description: 'URL of the file on your server'
    required: true
  release_id:
    description: 'Unique id for the release, e.g. git hash or semver'
    required: true
  release_name:
    description: 'Name for the release'
    required: true
  github_repository_url:
    description: 'URL of the repository'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.new_relic_user_api_key }}
    - ${{ inputs.new_relic_app_id }}
    - ${{ inputs.source_map }}
    - ${{ inputs.javascript_url }}
    - ${{ inputs.release_id }}
    - ${{ inputs.release_name }}
    - ${{ inputs.github_repository_url }}
