#!/bin/sh
#
# Upload sourcemap to New Relic

set -e

INPUT_API_KEY=$1
INPUT_APP_ID=$2
INPUT_SOURCEMAP_PATH=$3
INPUT_JS_URL=$4
INPUT_RELEASE_ID=$5
INPUT_RELEASE_NAME=$6
INPUT_GITHUB_REPOSITORY_URL=$7

if [ -z "${INPUT_RELEASE_ID}" ]; then
  INPUT_RELEASE_ID="${GITHUB_SHA}"
fi

if [ -z "${INPUT_RELEASE_NAME}" ]; then
  INPUT_RELEASE_NAME="${GITHUB_SHA}"
fi

curl -H "Api-Key: ${INPUT_API_KEY}" \
  -F "sourcemap=@${INPUT_SOURCEMAP_PATH}" \
  -F "javascriptUrl=${INPUT_JS_URL}" \
  -F "releaseId=${INPUT_RELEASE_ID}" \
  -F "releaseName=${INPUT_RELEASE_NAME}" \
  -F "repoUrl=${INPUT_GITHUB_REPOSITORY_URL}" \
  -F "buildCommit=${GITHUB_SHA}" \
  "https://sourcemaps.service.newrelic.com/v2/applications/${INPUT_APP_ID}/sourcemaps"
